import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * app的根布局
 * 根布局必须包含 html 和 body标签，其他布局不能包含这些标签
 * @param param0 
 * @returns 
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>我是根布局</div>
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
