import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "tang-nextjs",
  description: "Generated by create next app",
};

/**
 * app的根布局
 * 根布局必须包含 html 和 body标签，其他布局不能包含这些标签
 * @param param0 
 * @returns 
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  const container = false;
  
  const renderContainerOne = () => {
    return (
      <div className="container">
        <main className="content">
          <div className="inner">
            <div>我是根布局</div>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </div>
        </main>
        <div className="left"></div>
        <div className="right"></div>
      </div>
    );
  };

  const renderContainerTwo = () => {
    return (
      <div className="main-container">
        <main className="main-inner">
          <div>我是根布局</div>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </main>
      </div>
    );
  };

  return (
    <html lang="en">
      <body>
        <div className="root">
          {
            container ? renderContainerOne() : renderContainerTwo()
          }
        </div>
      </body>
    </html>
  );
}
